"""create table notebook

Revision ID: a65adceb0867
Revises: df918e4667ea
Create Date: 2024-06-14 17:02:37.798241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a65adceb0867'
down_revision: Union[str, None] = 'df918e4667ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notebook',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('header', sa.String(length=300), nullable=False),
    sa.Column('note', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notebook')
    # ### end Alembic commands ###
